version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-citas
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestor_citas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: gestor-citas
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gestor_citas
      PORT: 3000
      JWT_SECRET: supersecreto
    command: npm start

volumes:
  pgdata:
